#ifndef _PRE_COMPILER_OPTIONS_H
#define _PRE_COMPILER_OPTIONS_H
#define GPS_ON
#define ACCELEROMETER_ON
//#define RUNTIME_SERIAL_ON

#define TILT_MEASUREMENT_PERIOD 20
#define GPS_MEASUREMENT_PERIOD 2000

#endif
